PYTHON := /usr/bin/python3.8
SCRIPT := "/home/chibuikeejikeme/projects/rfcnlp/myworkrfc/src/log extraction/tcp_event_generator.py"
FUNCTION := run_zeek_script_on_pcap
ARGUMENTS := arg1 arg2
RESULTS := /home/chibuikeejikeme/projects/rfcnlp/myworkrfc/data/tcplog.xml

.PHONY: run
run:
	$(PYTHON) $(SCRIPT) > $(RESULTS)

